from enum import Enum


class DeprecationType(str, Enum):
    """String enum for deprecation types used in DbtDeprecationRefactor."""

    UNEXPECTED_JINJA_BLOCK_DEPRECATION = "UnexpectedJinjaBlockDeprecation"
    RESOURCE_NAMES_WITH_SPACES_DEPRECATION = "ResourceNamesWithSpacesDeprecation"
    PROPERTY_MOVED_TO_CONFIG_DEPRECATION = "PropertyMovedToConfigDeprecation"
    CUSTOM_KEY_IN_OBJECT_DEPRECATION = "CustomKeyInObjectDeprecation"
    MISSING_GENERIC_TEST_ARGUMENTS_PROPERTY_DEPRECATION = "MissingGenericTestArgumentsPropertyDeprecation"
    DUPLICATE_YAML_KEYS_DEPRECATION = "DuplicateYAMLKeysDeprecation"
    EXPOSURE_NAME_DEPRECATION = "ExposureNameDeprecation"
    CONFIG_LOG_PATH_DEPRECATION = "ConfigLogPathDeprecation"
    CONFIG_TARGET_PATH_DEPRECATION = "ConfigTargetPathDeprecation"
    CONFIG_DATA_PATH_DEPRECATION = "ConfigDataPathDeprecation"
    CONFIG_SOURCE_PATH_DEPRECATION = "ConfigSourcePathDeprecation"
    MISSING_PLUS_PREFIX_DEPRECATION = "MissingPlusPrefixDeprecation"
    CUSTOM_TOP_LEVEL_KEY_DEPRECATION = "CustomTopLevelKeyDeprecation"
    CUSTOM_KEY_IN_CONFIG_DEPRECATION = "CustomKeyInConfigDeprecation"


class ChangeType(str, Enum):
    """Fine-grained change type for each specific autofix operation.

    Every unique code path to generate a deprecation should have a unique change_type. This is helpful for ensuring locations are created correctly and if a specific change introduces a bug, it should be easier to identify where in the code the change was generated.
    """

    OWNER_FIELD_MOVED_TO_META_DEPRECATION = "OwnerFieldMovedToMetaDeprecation"
    PROPERTY_MOVED_TO_CONFIG_DEPRECATION = "PropertyMovedToConfigDeprecation"
    PROPERTY_ALREADY_IN_CONFIG_DEPRECATION = "PropertyAlreadyInConfigDeprecation"
    PROPERTY_OVERWRITTEN_IN_CONFIG_DEPRECATION = "PropertyOverwrittenInConfigDeprecation"
    PROPERTY_MISSPELLING_DEPRECATION = "PropertyMisspellingDeprecation"
    CUSTOM_KEY_MOVED_TO_META_DEPRECATION = "CustomKeyMovedToMetaDeprecation"
    CUSTOM_KEY_CLOSEST_MATCH_MOVED_TO_META_DEPRECATION = "CustomKeyClosestMatchMovedToMetaDeprecation"
    META_FIELDS_MERGED_DEPRECATION = "MetaFieldsMergedDeprecation"
    CUSTOM_CONFIG_RENAMED_DEPRECATION = "CustomConfigRenamedDeprecation"
    CUSTOM_CONFIG_MOVED_TO_META_DEPRECATION = "CustomConfigMovedToMetaDeprecation"
    CONFIG_GET_REFACTORED = "ConfigGetRefactored"
    UNMATCHED_ENDMACRO_DEPRECATION = "UnmatchedEndmacroDeprecation"
    UNMATCHED_ENDIF_DEPRECATION = "UnmatchedEndifDeprecation"
    SOURCE_FRESHNESS_PROJECT_HOOKS_NOT_RUN = "SourceFreshnessProjectHooksNotRun"
    SIMPLE_METRICS_MERGED_WITH_MODEL = "SimpleMetricsMergedWithModel"
    COMPLEX_METRICS_MERGED_WITH_MODEL = "ComplexMetricsMergedWithModel"
    METRICS_ADDED_FOR_MEASURES = "MetricsAddedForMeasures"
    SEMANTIC_MODEL_MERGED_WITH_MODEL = "SemanticModelMergedWithModel"
    TOP_LEVEL_SEMANTIC_MODEL_DELETED = "TopLevelSemanticModelDeleted"
    METRIC_TAGS_MIGRATION = "MetricTagsMigration"
    TOP_LEVEL_METRIC_DELETED = "TopLevelMetricDeleted"
    TOP_LEVEL_METRIC_UPDATED = "TopLevelMetricUpdated"
    FANCY_QUOTES_FIXUP = "FancyQuotesFixup"
    TAB_ONLY_LINE_FIXUP = "TabOnlyLineFixup"
    EXTRA_INDENTATION_FIXUP = "ExtraIndentationFixup"
    EXTRA_TABS_FIXUP = "ExtraTabsFixup"
    RESOURCE_NAME_WITH_SPACES_DEPRECATION = "ResourceNameWithSpacesDeprecation"
    EXPOSURE_NAME_DEPRECATION = "ExposureNameDeprecation"
    DUPLICATE_MODEL_REMOVED = "DuplicateModelRemoved"
    DUPLICATE_KEY_REMOVED = "DuplicateKeyRemoved"
    DEPRECATED_PROJECT_FIELD_REMOVED = "DeprecatedProjectFieldRemoved"
    DEPRECATED_PROJECT_FIELD_REMOVED_NON_DEFAULT = "DeprecatedProjectFieldRemovedNonDefault"
    DEPRECATED_PROJECT_FIELD_RENAMED = "DeprecatedProjectFieldRenamed"
    DEPRECATED_PROJECT_FIELD_MERGED = "DeprecatedProjectFieldMerged"
    MISSING_PLUS_PREFIX_DEPRECATION_FIX = "MissingPlusPrefixDeprecationFix"
    MISSING_GENERIC_TEST_ARGUMENTS_PROPERTY_DEPRECATION_FIX = "MissingGenericTestArgumentsPropertyDeprecationFix"
    SPACE_AFTER_PLUS_FIXUP = "SpaceAfterPlusFixup"
    INVALID_KEY_AFTER_PLUS_REMOVED = "InvalidKeyAfterPlusRemoved"
    SQL_FILE_RENAMED_FOR_SPACES = "SqlFileRenamedForSpaces"
    CUSTOM_TOP_LEVEL_KEY_REMOVED = "CustomTopLevelKeyRemoved"
    TEST_ARGUMENT_MOVED_TO_ARGUMENTS = "TestArgumentMovedToArguments"
    NODE_PROPERTY_MOVED_TO_CONFIG_DEPRECATION = "NodePropertyMovedToConfigDeprecation"
