"""Script to read conformance output and write to CSV.

Takes the conformance output that is generated by package_hub_fusion_compatibility
and converts it into CSV output for analysis.
Update OUTPUT_PATH, CONFORMANCE_OUTPUT_FILE_NAME, and FUSION_VERSION
Two CSVs are written to OUTPUT_PATH:
    "package_conformance_summary_v{fusion_version}_{run_date}.csv"
    "package_conformance_all_errors_v{fusion_version}_{run_date}.csv"
package_conformance_summary: one line per package version
package_conformance_all_errors: one line per error per package version
"""

import csv
import json
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any

OUTPUT_PATH: Path = Path.cwd() / "src" / "dbt_fusion_package_tools" / "scripts" / "output"
CONFORMANCE_OUTPUT_FILE_NAME: str = "conformance_autofix_output.json"
FUSION_VERSION = "101"


def reload_output_from_file(
    file_path: Path,
) -> dict[str, dict[str, dict[str, Any]]]:
    with file_path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def main():
    output_path: Path = OUTPUT_PATH
    conformance_output_file_name: str = CONFORMANCE_OUTPUT_FILE_NAME
    fusion_version = FUSION_VERSION
    run_date: str = datetime.today().strftime("%Y%m%d")
    package_summary_file_name: str = f"package_autofix_conformance_summary_v{fusion_version}_{run_date}.csv"
    conformance_output = reload_output_from_file(output_path / conformance_output_file_name)
    package_summary = []
    for package_name in conformance_output:
        package: dict[str, dict[str, Any]] = conformance_output[package_name]  # ty: ignore[invalid-assignment]
        for version in package:
            # package_version: dict[str, Any] = package[version]
            parse_compatible_hub = package[version]["parse_compatible_hub"]
            parse_compatible_pre_autofix = package[version]["parse_compatible_pre_autofix"]
            parse_compatible_post_autofix = package[version]["parse_compatible_post_autofix"]
            parse_compatible_hub_pre_mismatch = parse_compatible_hub != parse_compatible_pre_autofix
            parse_compatible_hub_true_pre_false = parse_compatible_hub is True and parse_compatible_pre_autofix is False
            parse_compatible_hub_true_post_false = parse_compatible_hub is True and parse_compatible_post_autofix is False
            parse_compatible_hub_false_pre_true = parse_compatible_hub is False and parse_compatible_pre_autofix is True
            parse_compatible_hub_false_post_true = parse_compatible_hub is False and parse_compatible_post_autofix is True
            v2_compatible_eligible = (parse_compatible_hub is False or parse_compatible_pre_autofix is False) and parse_compatible_post_autofix is True
            package_summary.append(
                {
                    "package_name": package_name,
                    "package_version": version,
                    "manually_verified_compatible": package[version]["manually_verified_compatible"],
                    "manually_verified_incompatible": package[version]["manually_verified_incompatible"],
                    "parse_compatible_hub": package[version]["parse_compatible_hub"],
                    "parse_compatible_pre_autofix": package[version]["parse_compatible_pre_autofix"],
                    "parse_compatible_post_autofix": package[version]["parse_compatible_post_autofix"],
                    "autofix_stdout_count": package[version].get("autofix_stdout_count"),
                    "autofix_stderr_count": package[version].get("autofix_stderr_count"),
                    "parse_errors_pre_autofix": package[version]["pre_autofix_parse_conformance"].get("total_errors"),
                    "parse_errors_post_autofix": package[version]["post_autofix_parse_conformance"].get("total_errors"),
                    "parse_compatible_hub_pre_mismatch": parse_compatible_hub_pre_mismatch,
                    "parse_compatible_hub_true_pre_false": parse_compatible_hub_true_pre_false,
                    "parse_compatible_hub_true_post_false": parse_compatible_hub_true_post_false,
                    "parse_compatible_hub_false_pre_true": parse_compatible_hub_false_pre_true,
                    "parse_compatible_hub_false_post_true": parse_compatible_hub_false_post_true,
                    "v2_compatible_eligible": v2_compatible_eligible,
                    "autofixed_version_file_name": package[version].get("autofixed_version_file_name")
                }
            )

    with open(output_path / package_summary_file_name, mode="w") as file:
        writer = csv.DictWriter(file, fieldnames=[field for field in package_summary[0]])
        writer.writeheader()
        writer.writerows(package_summary)
    print(f"Wrote {len(package_summary)} rows to {output_path / package_summary_file_name}")


if __name__ == "__main__":
    main()
