name: Run Nox on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  nox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: fjwillemsen/setup-nox2@v3.0.0
      - run: nox
