name: Run Nox on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  nox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # astral-sh/setup-uv@v10.0.1
      - uses: fjwillemsen/setup-nox2@da319daa4a57af7b0802d65173dd08b7e902fa08 # fjwillemsen/setup-nox2@v4.0.0
      - run: nox
