name: Run tests every hour to check JSON schema parsing

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # actions/checkout@v4
      - uses: astral-sh/setup-uv@e58605a9b6da7c637471fab8847a5e5a6b8df081 # astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      - run: uv sync --all-extras --all-packages
      - run: uv run pytest tests/e2e_tests/test_cli.py::test_check_latest_schema -v
      - run: uv run pytest
