name: Run Nox every hour to check JSON schema parsing

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  nox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
      - uses: fjwillemsen/setup-nox2@fc5420448a3f1145b0128f86b1837e82841684a4 # fjwillemsen/setup-nox2@v3.0.0
      - run: nox --session check_latest_schema-3.13
      - run: uv sync --all-extras --all-packages --python 3.13
      - run: uv run --python 3.13 pytest